{"Modified":"2019-10-03T00:03:00","Published":"2017-08-18T21:29:00","access":{"authentication":"NONE","complexity":"LOW","vector":"NETWORK"},"assigner":"cve@mitre.org","capec":[],"cvss":5,"cvss-time":"2019-10-03T00:03:00","cvss-vector":"AV:N/AC:L/Au:N/C:N/I:N/A:P","cwe":"CWE-617","id":"CVE-2017-12960","impact":{"availability":"PARTIAL","confidentiality":"NONE","integrity":"NONE"},"last-modified":"2019-10-03T00:03:00","references":["https://bugzilla.redhat.com/show_bug.cgi?id=1482433","https://savannah.gnu.org/forum/forum.php?forum_id=8936"],"refmap":{"confirm":["https://savannah.gnu.org/forum/forum.php?forum_id=8936"],"misc":["https://bugzilla.redhat.com/show_bug.cgi?id=1482433"]},"summary":"There is a reachable assertion abort in the function dict_rename_var() in data/dictionary.c of the libpspp library in GNU PSPP before 1.0.1 that will lead to remote denial of service.","vulnerable_configuration":[{"id":"cpe:2.3:a:gnu:pspp:0.11.0:*:*:*:*:*:*:*","title":"cpe:2.3:a:gnu:pspp:0.11.0:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:a:gnu:pspp:0.11.0:*:*:*:*:*:*:*"]}