{"Modified":"2021-07-21T11:39:00","Published":"2020-08-03T13:15:00","access":{"authentication":"NONE","complexity":"LOW","vector":"NETWORK"},"assigner":"psirt@us.ibm.com","capec":[],"cvss":6.4,"cvss-time":"2021-07-21T11:39:00","cvss-vector":"AV:N/AC:L/Au:N/C:P/I:N/A:P","cwe":"CWE-776","id":"CVE-2020-4377","impact":{"availability":"PARTIAL","confidentiality":"PARTIAL","integrity":"NONE"},"last-modified":"2021-07-21T11:39:00","references":["https://exchange.xforce.ibmcloud.com/vulnerabilities/179156","https://www.ibm.com/support/pages/node/6252853"],"refmap":{"confirm":["https://www.ibm.com/support/pages/node/6252853"],"xf":["ibm-cognos-cve20204377-xxe (179156)"]},"summary":"IBM Cognos Anaytics 11.0 and 11.1 is vulnerable to an XML External Entity Injection (XXE) attack when processing XML data. A remote attacker could exploit this vulnerability to expose sensitive information or consume memory resources. IBM X-Force ID: 179156.","vulnerable_configuration":[{"id":"cpe:2.3:a:ibm:cognos_analytics:11.0.0:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:cognos_analytics:11.0.0:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:ibm:cognos_analytics:11.1.0:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:cognos_analytics:11.1.0:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:a:ibm:cognos_analytics:11.0.0:*:*:*:*:*:*:*","cpe:2.3:a:ibm:cognos_analytics:11.1.0:*:*:*:*:*:*:*"]}