{"Modified":"2020-08-05T17:39:00","Published":"2020-07-24T23:15:00","access":{"authentication":"SINGLE","complexity":"MEDIUM","vector":"NETWORK"},"assigner":"cve@mitre.org","capec":[],"cvss":4.9,"cvss-time":"2020-08-05T17:39:00","cvss-vector":"AV:N/AC:M/Au:S/C:N/I:P/A:P","cwe":"CWE-476","id":"CVE-2020-10600","impact":{"availability":"PARTIAL","confidentiality":"NONE","integrity":"PARTIAL"},"last-modified":"2020-08-05T17:39:00","references":["https://us-cert.cisa.gov/ics/advisories/icsa-20-133-02"],"refmap":{"misc":["https://us-cert.cisa.gov/ics/advisories/icsa-20-133-02"]},"summary":"An authenticated remote attacker could crash PI Archive Subsystem when the subsystem is working under memory pressure. This can result in blocking queries to PI Data Archive (2018 SP2 and prior versions).","vulnerable_configuration":[{"id":"cpe:2.3:a:osisoft:pi_data_archive:3.4.430.460:*:*:*:*:*:*:*","title":"cpe:2.3:a:osisoft:pi_data_archive:3.4.430.460:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:osisoft:pi_data_archive:2018:-:*:*:*:*:*:*","title":"cpe:2.3:a:osisoft:pi_data_archive:2018:-:*:*:*:*:*:*"},{"id":"cpe:2.3:a:osisoft:pi_data_archive:2018:sp2:*:*:*:*:*:*","title":"cpe:2.3:a:osisoft:pi_data_archive:2018:sp2:*:*:*:*:*:*"},{"id":"cpe:2.3:a:osisoft:pi_data_archive:2019:*:*:*:*:*:*:*","title":"cpe:2.3:a:osisoft:pi_data_archive:2019:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:a:osisoft:pi_data_archive:3.4.430.460:*:*:*:*:*:*:*","cpe:2.3:a:osisoft:pi_data_archive:2018:-:*:*:*:*:*:*","cpe:2.3:a:osisoft:pi_data_archive:2018:sp2:*:*:*:*:*:*","cpe:2.3:a:osisoft:pi_data_archive:2019:*:*:*:*:*:*:*"]}