{"Modified":"2021-05-24T15:09:00","Published":"2021-05-17T17:15:00","access":{"authentication":"NONE","complexity":"LOW","vector":"NETWORK"},"assigner":"psirt@us.ibm.com","capec":[],"cvss":6.4,"cvss-time":"2021-05-24T15:09:00","cvss-vector":"AV:N/AC:L/Au:N/C:P/I:P/A:N","cwe":"CWE-862","id":"CVE-2020-4669","impact":{"availability":"NONE","confidentiality":"PARTIAL","integrity":"PARTIAL"},"last-modified":"2021-05-24T15:09:00","references":["https://www.ibm.com/support/pages/node/6436821","https://exchange.xforce.ibmcloud.com/vulnerabilities/186400"],"summary":"IBM Planning Analytics Local 2.0 connects to a MongoDB server. MongoDB, a document-oriented database system, is listening on the remote port, and it is configured to allow connections without password authentication. A remote attacker can gain unauthorized access to the database. IBM X-Force ID: 184600.","vulnerable_configuration":[{"id":"cpe:2.3:a:ibm:planning_analytics_cloud:2.0.0:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:planning_analytics_cloud:2.0.0:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:ibm:planning_analytics_local:2.0.0:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:planning_analytics_local:2.0.0:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:a:ibm:planning_analytics_cloud:2.0.0:*:*:*:*:*:*:*","cpe:2.3:a:ibm:planning_analytics_local:2.0.0:*:*:*:*:*:*:*"]}