{"Modified":"2020-02-24T18:56:00","Published":"2020-02-19T16:15:00","access":{"authentication":"SINGLE","complexity":"LOW","vector":"NETWORK"},"assigner":"cve@mitre.org","capec":[],"cvss":4,"cvss-time":"2020-02-24T18:56:00","cvss-vector":"AV:N/AC:L/Au:S/C:N/I:N/A:P","cwe":"NVD-CWE-noinfo","id":"CVE-2020-4200","impact":{"availability":"PARTIAL","confidentiality":"NONE","integrity":"NONE"},"last-modified":"2020-02-24T18:56:00","references":["https://exchange.xforce.ibmcloud.com/vulnerabilities/174914","https://www.ibm.com/support/pages/node/2875251"],"refmap":{"confirm":["https://www.ibm.com/support/pages/node/2875251"],"xf":["ibm-db2-cve20204200-dos (174914)"]},"summary":"IBM DB2 for Linux, UNIX and Windows (includes DB2 Connect Server) 10.5, 11.1, and 11.5 could allow an authenticated attacker to send specially crafted commands to cause a denial of service. IBM X-Force ID: 174914.","vulnerable_configuration":[{"id":"cpe:2.3:a:ibm:db2:10.5:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:db2:10.5:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:ibm:db2:11.1:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:db2:11.1:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:ibm:db2:11.5:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:db2:11.5:*:*:*:*:*:*:*"},{"id":"cpe:2.3:o:ibm:aix:-:*:*:*:*:*:*:*","title":"cpe:2.3:o:ibm:aix:-:*:*:*:*:*:*:*"},{"id":"cpe:2.3:o:linux:linux_kernel:-:*:*:*:*:*:*:*","title":"cpe:2.3:o:linux:linux_kernel:-:*:*:*:*:*:*:*"},{"id":"cpe:2.3:o:microsoft:windows:-:*:*:*:*:*:*:*","title":"cpe:2.3:o:microsoft:windows:-:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:a:ibm:db2:10.5:*:*:*:*:*:*:*","cpe:2.3:a:ibm:db2:11.1:*:*:*:*:*:*:*","cpe:2.3:a:ibm:db2:11.5:*:*:*:*:*:*:*"]}