{"Modified":"2020-06-05T20:17:00","Published":"2020-06-04T14:15:00","access":{"authentication":"NONE","complexity":"LOW","vector":"NETWORK"},"assigner":"cve@mitre.org","capec":[],"cvss":5,"cvss-time":"2020-06-05T20:17:00","cvss-vector":"AV:N/AC:L/Au:N/C:P/I:N/A:N","cwe":"CWE-307","id":"CVE-2020-4193","impact":{"availability":"NONE","confidentiality":"PARTIAL","integrity":"NONE"},"last-modified":"2020-06-05T20:17:00","references":["https://exchange.xforce.ibmcloud.com/vulnerabilities/174857","https://www.ibm.com/support/pages/node/6220132"],"refmap":{"confirm":["https://www.ibm.com/support/pages/node/6220132"],"xf":["ibm-guardium-cve20204193-info-disc (174857)"]},"summary":"IBM Security Guardium 11.1 uses an inadequate account lockout setting that could allow a remote attacker to brute force account credentials. IBM X-Force ID: 174857.","vulnerable_configuration":[{"id":"cpe:2.3:a:ibm:security_guardium:11.1:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:security_guardium:11.1:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:a:ibm:security_guardium:11.1:*:*:*:*:*:*:*"]}