{"Modified":"2019-08-30T13:18:00","Published":"2019-08-26T18:15:00","access":{"authentication":"NONE","complexity":"LOW","vector":"NETWORK"},"assigner":"cve@mitre.org","capec":[],"cvss":5,"cvss-time":"2019-08-30T13:18:00","cvss-vector":"AV:N/AC:L/Au:N/C:N/I:N/A:P","cwe":"CWE-191","id":"CVE-2018-20989","impact":{"availability":"PARTIAL","confidentiality":"NONE","integrity":"NONE"},"last-modified":"2019-08-30T13:18:00","references":["https://rustsec.org/advisories/RUSTSEC-2018-0001.html"],"refmap":{"misc":["https://rustsec.org/advisories/RUSTSEC-2018-0001.html"]},"summary":"An issue was discovered in the untrusted crate before 0.6.2 for Rust. Error handling can trigger an integer underflow and panic.","vulnerable_configuration":[{"id":"cpe:2.3:a:untrusted_project:untrusted:-:*:*:*:*:*:*:*","title":"cpe:2.3:a:untrusted_project:untrusted:-:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:untrusted_project:untrusted:0.5.1:*:*:*:*:*:*:*","title":"cpe:2.3:a:untrusted_project:untrusted:0.5.1:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:untrusted_project:untrusted:0.6.0:*:*:*:*:*:*:*","title":"cpe:2.3:a:untrusted_project:untrusted:0.6.0:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:a:untrusted_project:untrusted:-:*:*:*:*:*:*:*","cpe:2.3:a:untrusted_project:untrusted:0.5.1:*:*:*:*:*:*:*","cpe:2.3:a:untrusted_project:untrusted:0.6.0:*:*:*:*:*:*:*"]}