{"Modified":"2023-03-30T22:15:00","Published":"2023-03-26T19:15:00","access":{},"assigner":"cve@mitre.org","cvss":null,"cwe":"Unknown","id":"CVE-2023-28859","impact":{},"last-modified":"2023-03-30T22:15:00","references":["https://github.com/redis/redis-py/pull/2641","https://github.com/redis/redis-py/issues/2665","https://github.com/redis/redis-py/releases/tag/v4.4.4","https://github.com/redis/redis-py/releases/tag/v4.5.4","https://github.com/redis/redis-py/pull/2666"],"summary":"redis-py before 4.4.4 and 4.5.x before 4.5.4 leaves a connection open after canceling an async Redis command at an inopportune time, and can send response data to the client of an unrelated request. (This could, for example, happen for a non-pipeline operation.) NOTE: the solutions for CVE-2023-28859 address data leakage across AsyncIO connections in general.","vulnerable_configuration":[],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":[]}