{"Modified":"2020-08-24T17:37:00","Published":"2019-01-02T15:29:00","access":{"authentication":"NONE","complexity":"MEDIUM","vector":"NETWORK"},"assigner":"cve@mitre.org","capec":[],"cvss":4.3,"cvss-time":"2020-08-24T17:37:00","cvss-vector":"AV:N/AC:M/Au:N/C:N/I:N/A:P","cwe":"CWE-835","id":"CVE-2019-3573","impact":{"availability":"PARTIAL","confidentiality":"NONE","integrity":"NONE"},"last-modified":"2020-08-24T17:37:00","references":["https://github.com/saitoha/libsixel/issues/83","https://github.com/TeamSeri0us/pocs/tree/master/libsixel"],"refmap":{"misc":["https://github.com/TeamSeri0us/pocs/tree/master/libsixel","https://github.com/saitoha/libsixel/issues/83"]},"summary":"In libsixel v1.8.2, there is an infinite loop in the function sixel_decode_raw_impl() in the file fromsixel.c, as demonstrated by sixel2png.","vulnerable_configuration":[{"id":"cpe:2.3:a:libsixel_project:libsixel:1.8.2:*:*:*:*:*:*:*","title":"cpe:2.3:a:libsixel_project:libsixel:1.8.2:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:a:libsixel_project:libsixel:1.8.2:*:*:*:*:*:*:*"]}