{"Modified":"2020-04-30T19:07:00","Published":"2019-10-10T14:15:00","access":{"authentication":"NONE","complexity":"LOW","vector":"LOCAL"},"assigner":"cve@mitre.org","capec":[],"cvss":2.1,"cvss-time":"2020-04-30T19:07:00","cvss-vector":"AV:L/AC:L/Au:N/C:P/I:N/A:N","cwe":"CWE-922","id":"CVE-2019-4265","impact":{"availability":"NONE","confidentiality":"PARTIAL","integrity":"NONE"},"last-modified":"2020-04-30T19:07:00","references":["https://exchange.xforce.ibmcloud.com/vulnerabilities/160198","https://www.ibm.com/support/pages/node/1078995"],"refmap":{"confirm":["https://www.ibm.com/support/pages/node/1078995"],"xf":["ibm-maximo-cve20194265-info-disc (160198)"]},"summary":"IBM Maximo Anywhere 7.6.0, 7.6.1, 7.6.2, and 7.6.3 does not have device root detection which could result in an attacker gaining sensitive information about the device. IBM X-Force ID: 160198.","vulnerable_configuration":[{"id":"cpe:2.3:a:ibm:maximo_anywhere:7.6.0.0:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:maximo_anywhere:7.6.0.0:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:ibm:maximo_anywhere:7.6.1.0:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:maximo_anywhere:7.6.1.0:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:ibm:maximo_anywhere:7.6.2.0:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:maximo_anywhere:7.6.2.0:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:ibm:maximo_anywhere:7.6.3.0:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:maximo_anywhere:7.6.3.0:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:a:ibm:maximo_anywhere:7.6.0.0:*:*:*:*:*:*:*","cpe:2.3:a:ibm:maximo_anywhere:7.6.1.0:*:*:*:*:*:*:*","cpe:2.3:a:ibm:maximo_anywhere:7.6.2.0:*:*:*:*:*:*:*","cpe:2.3:a:ibm:maximo_anywhere:7.6.3.0:*:*:*:*:*:*:*"]}