{"Modified":"2019-07-04T11:15:00","Published":"2019-07-01T15:15:00","access":{"authentication":"SINGLE","complexity":"LOW","vector":"NETWORK"},"assigner":"cve@mitre.org","capec":[],"cvss":4,"cvss-time":"2019-07-04T11:15:00","cvss-vector":"AV:N/AC:L/Au:S/C:N/I:N/A:P","cwe":"CWE-749","id":"CVE-2019-4386","impact":{"availability":"PARTIAL","confidentiality":"NONE","integrity":"NONE"},"last-modified":"2019-07-04T11:15:00","references":["http://www.securityfocus.com/bid/109019","https://exchange.xforce.ibmcloud.com/vulnerabilities/162174","https://www.ibm.com/support/docview.wss?uid=ibm10886809"],"refmap":{"bid":["109019"],"confirm":["https://www.ibm.com/support/docview.wss?uid=ibm10886809"],"xf":["ibm-db2-cve20194386-dos (162174)"]},"summary":"IBM DB2 for Linux, UNIX and Windows (includes DB2 Connect Server) 11.1 could allow an authenticated user to execute a function that would cause the server to crash. IBM X-Force ID: 162714.","vulnerable_configuration":[{"id":"cpe:2.3:a:ibm:db2:11.1.3:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:db2:11.1.3:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:ibm:db2:11.1.3.2:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:db2:11.1.3.2:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:ibm:db2:11.1.3.3:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:db2:11.1.3.3:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:ibm:db2:11.1.4:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:db2:11.1.4:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:ibm:db2:11.1.4.4:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:db2:11.1.4.4:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:a:ibm:db2:11.1.3:*:*:*:*:*:*:*","cpe:2.3:a:ibm:db2:11.1.3.2:*:*:*:*:*:*:*","cpe:2.3:a:ibm:db2:11.1.3.3:*:*:*:*:*:*:*","cpe:2.3:a:ibm:db2:11.1.4:*:*:*:*:*:*:*","cpe:2.3:a:ibm:db2:11.1.4.4:*:*:*:*:*:*:*"]}